FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/Flowlist.Core/Flowlist.Core.csproj Flowlist.Core/
COPY src/Flowlist.Infrastructure/Flowlist.Infrastructure.csproj Flowlist.Infrastructure/
COPY src/Hosts/Flowist.Host.TelegramBot/Flowist.Host.TelegramBot.csproj Hosts/Flowist.Host.TelegramBot/

RUN dotnet restore Hosts/Flowist.Host.TelegramBot/Flowist.Host.TelegramBot.csproj

COPY src/ .

WORKDIR /src/Hosts/Flowist.Host.TelegramBot
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Flowist.Host.TelegramBot.dll"]