from mcr.microsoft.com/dotnet/sdk:8.0 as build
workdir /src

copy src/Core/Flowlist.Core/Flowlist.Core.csproj Core/Flowlist.Core/
copy src/Infrastructure/Flowist.Infrastructure/Flowist.Infrastructure.csproj Infrastructure/Flowist.Infrastructure/
copy src/Presentation/TelegramBot/Flowist.TelegramBot/Flowist.TelegramBot.csproj Presentation/TelegramBot/Flowist.TelegramBot/

run dotnet restore Presentation/TelegramBot/Flowist.TelegramBot/Flowist.TelegramBot.csproj

copy src/ .

workdir /src/Presentation/TelegramBot/Flowist.TelegramBot
run dotnet publish -c Release -o /app/publish

from mcr.microsoft.com/dotnet/aspnet:8.0
workdir /app
copy --from=build /app/publish .
entrypoint ["dotnet", "Flowist.TelegramBot.dll"]