FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/Flowlist.Core/Flowlist.Core.csproj Flowlist.Core/
COPY src/Flowlist.Infrastructure/Flowlist.Infrastructure.csproj Flowlist.Infrastructure/
COPY src/Hosts/Flowist.Host.ApiGateway/Flowist.Host.ApiGateway.csproj Hosts/Flowist.Host.ApiGateway/

RUN dotnet restore Hosts/Flowist.Host.ApiGateway/Flowist.Host.ApiGateway.csproj

COPY src/ .

WORKDIR /src/Hosts/Flowist.Host.ApiGateway
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Flowist.Host.ApiGateway.dll"]